--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants
branches:
  - master
projects:
  PiggyCustomEnchants:
    path: ""
    icon: "resources/PCE_Icon.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: Paroxity/Commando/Commando
        version: ^2.1.0
    lint: false
...