name: PiggyCustomEnchants
main: DaPigGuy\PiggyCustomEnchants\PiggyCustomEnchants
version: 2.1.1
api: 3.11.2
load: POSTWORLD
author: DaPigGuy
website: "https://github.com/DaPigGuy/PiggyCustomEnchants/"
permissions:
  piggycustomenchants:
    default: false
    description: "Use everything in PiggyCustomEnchants"
    children:
      piggycustomenchants.command:
        default: op
        description: "Use all PiggyCustomEnchants commands"
        children:
          piggycustomenchants.command.ce:
            default: op
            description: "Use /customenchant"
            children:
              piggycustomenchants.command.ce.about:
                default: true
                description: "Use /customenchant about"
              piggycustomenchants.command.ce.enchant:
                default: op
                description: "Use /customenchant enchant"
              piggycustomenchants.command.ce.help:
                default: true
                description: "Use /customenchant help"
              piggycustomenchants.command.ce.info:
                default: true
                description: "Use /customenchant info"
              piggycustomenchants.command.ce.list:
                default: true
                description: "Use /customenchant list"
              piggycustomenchants.command.ce.nbt:
                default: true
                description: "Use /customenchant nbt"
              piggycustomenchants.command.ce.remove:
                default: op
                description: "Use /customenchant remove"
      piggycustomenchants.overridecheck:
        default: false
        description: "Override the check and enchant any item with any enchant"
