name: PiggyCustomEnchants
main: PiggyCustomEnchants\Main
version: 1.0.7
api: 3.0.0-ALPHA9
load: POSTWORLD
author: DaPigGuy
permissions:
  piggycustomenchants:
    default: false
    description: "Use everything in PiggyCustomEnchants"
    children:
      piggycustomenchants.command:
        default: op
        description: "use all PiggyCustomEnchants commands"
        children:
          piggycustomenchants.command.ce:
            default: op
            description: "Use /customenchant"
            children:
              piggycustomenchants.command.ce.about:
                default: true
                description: "Use /customenchant about"
              piggycustomenchants.command.ce.enchant:
                default: op
                description: "Use /customenchant enchant"
              piggycustomenchants.command.ce.help:
                default: true
                description: "Use /customenchant help"
              piggycustomenchants.command.ce.list:
                default: true
                description: "Use /customenchant list"
              piggycustomenchants.command.ce.info:
                default: true
                description: "Use /customenchant info"
      piggycustomenchants.overridecheck:
        default: false
        description: "Override the check and enchant any item with any enchant"
